name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  nix-validate:
    name: Nix Validate
    uses: dryvist/.github/.github/workflows/_nix-validate.yml@main
    with:
      all_systems: false
